// Shared by the live/GNU oracle and the catalog/live CLI self-check.
pub const EXPRESSIONS: &[&[&str]] = &[
    &[],
    &["-name", "*"],
    &["-type", "f,d"],
    &["-type", "l"],
    &["-false"],
    &["-maxdepth", "0", "-print"],
    &["-depth"],
    &["-depth", "-maxdepth", "1"],
    &["-mindepth", "2"],
    &["-xdev"],
    &["-mount", "-name", "*.c"],
    &["-name", "dir", "-prune", "-o", "-print"],
    &["-depth", "-prune"],
    &["-print", "-quit"],
    &["-quit"],
    &["-name", "*.c", "-print", "-quit"],
    &["-name", "*.c", "-o", "-name", "*.txt"],
    &["-name", "*.c", "-o", "-name", "*.txt", "-print"],
    &["(", "-name", "*.c", "-o", "-name", "*.txt", ")", "-print0"],
    &["-false", ",", "-name", "a.c"],
    &["!", "-type", "d"],
    &["-name", "[[:alpha:]]*"],
    &["-iname", "[^a]*"],
    &["-name", "[]a]*"],
    &["-name", "[a-z]*"],
    &["-name", "\\.*"],
    &["-path", "*dir*file"],
    &["-name", "["],
    &["-name", "*\\"],
    &["-name", "[[:space:]]*"],
    &["-iname", "[[:upper:]]*"],
    &["-iname", "[![:upper:]]*"],
    &["-iname", "[A-z]*"],
    &["-iname", "[Z-a]*"],
    &["-iname", "[[=a=]]*"],
    &["-iname", "[[.a.]-[.c.]]*"],
    &["-perm", "644"],
    &["-perm", "-u+r"],
    &["-perm", "u=rw,g+r"],
    &["-perm", "a+x"],
    &["-perm", "o-w"],
    &["-perm", "a+X"],
    &["-perm", "u+s"],
    &["-perm", "a+t"],
    &["-perm", "/000"],
    &["-perm", "-000"],
    &["-size", "0c"],
    &["-size", "-1k"],
    &["-size", "2k"],
    &["-size", "0"],
    &["-size", "-1"],
    &["-size", "1w"],
    &["-size", "1b"],
    &["-size", "1M"],
    &["-size", "1G"],
    &["-mtime", "0"],
    &["-atime", "0"],
    &["-ctime", "0"],
    &["-mmin", "+1"],
    &["-amin", "1"],
    &["-cmin", "1"],
    &["-mmin", "0.5"],
    &["-mtime", "1.5"],
    &["-mtime", "18446744073709551616"],
    &["-daystart", "-mtime", "0"],
    &["-used", "0"],
    &["-links", "1"],
    &["-inum", "0"],
    &["-uid", "0"],
    &["-gid", "0"],
    &["-user", "root"],
    &["-group", "root"],
    &["-nouser"],
    &["-nogroup"],
    &["-readable"],
    &["-writable"],
    &["-executable"],
    &["-empty"],
    &["-newer", "@REFERENCE@"],
    &["-anewer", "@REFERENCE@"],
    &["-cnewer", "@REFERENCE@"],
    &["-newermm", "@REFERENCE@"],
    &["-neweram", "@REFERENCE@"],
    &["-newercm", "@REFERENCE@"],
    &["-newermc", "@REFERENCE@"],
    &["-newermt", "-30 minutes"],
    &["-newermt", "-10 minutes"],
    &["-newermt", "1 hour ago"],
    &["-newermt", "-2 hours"],
    &["-newermt", "-6 hours"],
    &["-newermt", "-5 minutes"],
    &["-newermt", "-300 seconds"],
    &["-newermt", "-1 day"],
    &["-newermt", "-1 hour"],
    &["-newermt", "now"],
    &["-newermt", "@0"],
    &["-newermt", "2021-02-15 00:00:00"],
    &["-newermt", "today"],
    &["-newermt", "yesterday"],
    &["-newermt", "1970-01-01"],
    &["-samefile", "@REFERENCE@"],
    &["-fstype", "proc"],
    &["-fstype", "local"],
    &["-fstype", "rdonly"],
    &[
        "-noleaf",
        "-warn",
        "-nowarn",
        "-ignore_readdir_race",
        "-noignore_readdir_race",
    ],
];
