//! Bracket expressions: ranges, negation, escapes, POSIX classes, and the
//! malformed shapes git silently never matches.

use super::{File, Ignore, Row, Unmatched, assert_rows};

pub(super) const ROWS: &[Row] = &[
    // Ranges and members.
    ("range", "[a-c].txt\n", "b.txt", File, Ignore),
    ("outside the range", "[a-c].txt\n", "d.txt", File, Unmatched),
    (
        "class is one byte",
        "[a-c].txt\n",
        "ab.txt",
        File,
        Unmatched,
    ),
    ("trailing hyphen is a member", "[a-]\n", "-", File, Ignore),
    (
        "trailing hyphen is no range",
        "[a-]\n",
        "b",
        File,
        Unmatched,
    ),
    ("leading hyphen is a member", "[-a]\n", "-", File, Ignore),
    ("escaped hyphen is a member", "[a\\-c]\n", "-", File, Ignore),
    (
        "escaped hyphen is not a range",
        "[a\\-c]\n",
        "b",
        File,
        Unmatched,
    ),
    ("escaped range start", "[\\a-c]\n", "b", File, Ignore),
    (
        "escaped bracket inside a class",
        "[a\\]]\n",
        "]",
        File,
        Ignore,
    ),
    (
        "reversed range keeps its start",
        "[z-a]\n",
        "z",
        File,
        Ignore,
    ),
    (
        "reversed range has no interior",
        "[z-a]\n",
        "m",
        File,
        Unmatched,
    ),
    (
        "reversed range drops its end",
        "[z-a]\n",
        "a",
        File,
        Unmatched,
    ),
    ("range after a member", "[xa-c]\n", "b", File, Ignore),
    ("class is case-sensitive", "[A-Z]\n", "a", File, Unmatched),
    // Negation.
    ("negated class !", "[!a].txt\n", "b.txt", File, Ignore),
    (
        "negated class ! excludes",
        "[!a].txt\n",
        "a.txt",
        File,
        Unmatched,
    ),
    ("negated class ^", "[^b].log\n", "a.log", File, Ignore),
    (
        "negated class ^ excludes",
        "[^b].log\n",
        "b.log",
        File,
        Unmatched,
    ),
    ("escaped bang is a member", "[\\!a]\n", "!", File, Ignore),
    (
        "escaped bang does not negate",
        "[\\!a]\n",
        "b",
        File,
        Unmatched,
    ),
    (
        "negated class takes one byte of a scalar",
        "[!a]?\n",
        "é",
        File,
        Ignore,
    ),
    (
        "negated class alone cannot take a scalar",
        "[!a]\n",
        "é",
        File,
        Unmatched,
    ),
    // `]` first is a member.
    ("] first in class", "[]a].dat\n", "].dat", File, Ignore),
    (
        "] first, then a member",
        "[]a].dat\n",
        "a.dat",
        File,
        Ignore,
    ),
    (
        "] first is not everything",
        "[]a].dat\n",
        "b.dat",
        File,
        Unmatched,
    ),
    (
        "] first after negation",
        "[!]a].dat\n",
        "].dat",
        File,
        Unmatched,
    ),
    (
        "] first after negation excludes",
        "[!]a].dat\n",
        "b.dat",
        File,
        Ignore,
    ),
    // POSIX classes.
    (
        "escaped byte in POSIX name is not syntax",
        "[[:digi\\t:]]\n",
        "5",
        File,
        Unmatched,
    ),
    (
        "range hyphen before POSIX syntax does not absorb digits",
        "[a-[:digit:]]\n",
        "5",
        File,
        Unmatched,
    ),
    (
        "raw class close leaves trailing bracket literal",
        "[a-[:digit:]]\n",
        "a]",
        File,
        Ignore,
    ),
    (
        "POSIX space excludes form feed",
        "[[:space:]]\n",
        "\u{000c}",
        File,
        Unmatched,
    ),
    ("POSIX digit", "[[:digit:]]\n", "7", File, Ignore),
    (
        "POSIX digit excludes",
        "[[:digit:]]\n",
        "x",
        File,
        Unmatched,
    ),
    (
        "POSIX class beside a member",
        "[[:digit:]x]\n",
        "x",
        File,
        Ignore,
    ),
    (
        "member beside a POSIX class",
        "[[:digit:]x]\n",
        "7",
        File,
        Ignore,
    ),
    ("negated POSIX class", "[![:digit:]]\n", "x", File, Ignore),
    (
        "negated POSIX class excludes",
        "[![:digit:]]\n",
        "7",
        File,
        Unmatched,
    ),
    (
        "range beside a POSIX class",
        "[a-c[:digit:]]\n",
        "5",
        File,
        Ignore,
    ),
    ("unknown POSIX class", "[[:bogus:]]\n", "7", File, Unmatched),
    (
        "unknown POSIX class is not data",
        "[[:bogus:]]\n",
        "b",
        File,
        Unmatched,
    ),
    ("alnum", "[[:alnum:]]\n", "A", File, Ignore),
    ("alnum excludes", "[[:alnum:]]\n", "_", File, Unmatched),
    ("alpha", "[[:alpha:]]\n", "z", File, Ignore),
    ("alpha excludes", "[[:alpha:]]\n", "5", File, Unmatched),
    ("blank", "[[:blank:]]\n", "\t", File, Ignore),
    ("blank excludes", "[[:blank:]]\n", "x", File, Unmatched),
    ("cntrl", "[[:cntrl:]]\n", "\u{7f}", File, Ignore),
    ("cntrl excludes", "[[:cntrl:]]\n", "a", File, Unmatched),
    ("graph", "[[:graph:]]\n", "!", File, Ignore),
    (
        "graph excludes space",
        "x[[:graph:]]\n",
        "x ",
        File,
        Unmatched,
    ),
    ("lower", "[[:lower:]]\n", "a", File, Ignore),
    ("lower excludes", "[[:lower:]]\n", "A", File, Unmatched),
    ("print", "x[[:print:]]\n", "x ", File, Ignore),
    ("print excludes tab", "[[:print:]]\n", "\t", File, Unmatched),
    ("punct", "[[:punct:]]\n", "!", File, Ignore),
    ("punct excludes", "[[:punct:]]\n", "a", File, Unmatched),
    ("space", "[[:space:]]\n", "\t", File, Ignore),
    ("space excludes", "[[:space:]]\n", "a", File, Unmatched),
    ("upper", "[[:upper:]]\n", "A", File, Ignore),
    ("upper excludes", "[[:upper:]]\n", "a", File, Unmatched),
    ("xdigit", "[[:xdigit:]]\n", "F", File, Ignore),
    ("xdigit excludes", "[[:xdigit:]]\n", "g", File, Unmatched),
    // Classes git never matches.
    ("unclosed class", "[abc\n", "[abc", File, Unmatched),
    ("unclosed class is no class", "[abc\n", "a", File, Unmatched),
    ("empty class", "[]\n", "[]", File, Unmatched),
    (
        "slash in a class is a separator",
        "left[/]right\n",
        "left/right",
        File,
        Unmatched,
    ),
    (
        "brace is literal",
        "{red,blue}\n",
        "{red,blue}",
        File,
        Ignore,
    ),
    (
        "brace is no alternation",
        "{red,blue}\n",
        "red",
        File,
        Unmatched,
    ),
];

#[test]
fn bracket_expressions() {
    assert_rows(ROWS);
}
