//! Negation and last-match-wins within one ignore file. The full matrix of
//! fast-path buckets is in `buckets`.

use super::{Dir, File, Ignore, Row, Unmatched, Whitelist, assert_rows};

pub(super) const ROWS: &[Row] = &[
    (
        "negation wins when later",
        "*.tmp\n!important.tmp\n",
        "important.tmp",
        File,
        Whitelist,
    ),
    (
        "negation loses when earlier",
        "!important.tmp\n*.tmp\n",
        "important.tmp",
        File,
        Ignore,
    ),
    (
        "negation spares non-matching paths",
        "*.tmp\n!important.tmp\n",
        "other.tmp",
        File,
        Ignore,
    ),
    (
        "re-ignored after a negation",
        "*.bak\n!keep.bak\n*.bak\n",
        "keep.bak",
        File,
        Ignore,
    ),
    (
        "negation of a negation's target again",
        "*.bak\n!keep.bak\n*.bak\n!keep.bak\n",
        "keep.bak",
        File,
        Whitelist,
    ),
    (
        "negation alone still reports",
        "!solo\n",
        "solo",
        File,
        Whitelist,
    ),
    (
        "negation alone spares others",
        "!solo\n",
        "other",
        File,
        Unmatched,
    ),
    ("lone bang is no pattern", "!\n", "!", File, Unmatched),
    ("lone bang does not negate", "x\n!\n", "x", File, Ignore),
    (
        "negated anchored pattern",
        "*.c\n!/src/*.c\n",
        "src/a.c",
        File,
        Whitelist,
    ),
    (
        "negated anchored pattern stays anchored",
        "*.c\n!/src/*.c\n",
        "lib/src/a.c",
        File,
        Ignore,
    ),
    (
        "directory-only negation spares files",
        "foo\n!foo/\n",
        "foo",
        File,
        Ignore,
    ),
    (
        "directory-only negation takes directories",
        "foo\n!foo/\n",
        "foo",
        Dir,
        Whitelist,
    ),
    (
        "later non-matching extension",
        "*.rs\n!*.txt\n",
        "a.rs",
        File,
        Ignore,
    ),
    (
        "later non-matching prefix",
        "foo*\n!fob*\n",
        "foo.rs",
        File,
        Ignore,
    ),
    (
        "later non-matching suffix",
        "*o.rs\n!*x.rs\n",
        "foo.rs",
        File,
        Ignore,
    ),
    (
        "later non-matching literal",
        "foo.rs\n!bar.rs\n",
        "foo.rs",
        File,
        Ignore,
    ),
    (
        "later non-matching general",
        "f*o.rs\n!b*o.rs\n",
        "foo.rs",
        File,
        Ignore,
    ),
    (
        "later non-matching anchored",
        "src/*.rs\n!src/*.c\n",
        "src/a.rs",
        File,
        Ignore,
    ),
    (
        "earlier matching entry in the same bucket",
        "!*.rs\n*.txt\n",
        "a.rs",
        File,
        Whitelist,
    ),
    (
        "same bucket, two matches, later wins",
        "foo*\n!fo*\n",
        "foo.rs",
        File,
        Whitelist,
    ),
    (
        "same bucket, two matches, later ignores",
        "!fo*\nfoo*\n",
        "foo.rs",
        File,
        Ignore,
    ),
    (
        "extension beside a multi-dot suffix",
        "*.tar.gz\n!*.gz\n",
        "x.tar.gz",
        File,
        Whitelist,
    ),
    (
        "multi-dot suffix beside an extension",
        "!*.gz\n*.tar.gz\n",
        "x.tar.gz",
        File,
        Ignore,
    ),
    ("multi-dot suffix", "*.tar.gz\n", "x.tar.gz", File, Ignore),
    (
        "multi-dot suffix is whole",
        "*.tar.gz\n",
        "x.gz",
        File,
        Unmatched,
    ),
    (
        "extension is the last dot",
        "*.gz\n",
        "x.tar.gz",
        File,
        Ignore,
    ),
    ("extension needs its dot", "*.gz\n", "xgz", File, Unmatched),
    (
        "general prefix and literal",
        "foo*\n!foobar\n",
        "foobar",
        File,
        Whitelist,
    ),
    (
        "literal and general prefix",
        "!foobar\nfoo*\n",
        "foobar",
        File,
        Ignore,
    ),
    (
        "fixed suffix and extension",
        "*.gc??\n!*.gcda\n",
        "x.gcda",
        File,
        Whitelist,
    ),
    (
        "extension and fixed suffix",
        "!*.gcda\n*.gc??\n",
        "x.gcda",
        File,
        Ignore,
    ),
    (
        "anchored general and anchored literal",
        "Doc/*/x\n!Doc/a/x\n",
        "Doc/a/x",
        File,
        Whitelist,
    ),
    (
        "anchored literal and anchored general",
        "!Doc/a/x\nDoc/*/x\n",
        "Doc/a/x",
        File,
        Ignore,
    ),
    (
        "contains and literal",
        "*mid*\n!amidb\n",
        "amidb",
        File,
        Whitelist,
    ),
    (
        "literal and contains",
        "!amidb\n*mid*\n",
        "amidb",
        File,
        Ignore,
    ),
    (
        "negation, earlier spelling",
        "*.log\n!important.log\n",
        "important.log",
        File,
        Whitelist,
    ),
    (
        "last match, earlier spelling",
        "!important.log\n*.log\n",
        "important.log",
        File,
        Ignore,
    ),
];

#[test]
fn negation_and_order() {
    assert_rows(ROWS);
}
