//! Line syntax: blanks, comments, escapes, trailing spaces, `?` and `*`.

use super::super::Pattern;
use super::{Case, Dir, File, Gitignore, Ignore, Row, Unmatched, assert_cases, assert_rows};
use std::path::Path;

pub(super) const ROWS: &[Row] = &[
    // Blank and comment lines.
    ("blank line", "\n", "anything", File, Unmatched),
    ("spaces-only line is blank", "   \n", " ", File, Unmatched),
    (
        "comment",
        "# generated by build\n",
        "# generated by build",
        File,
        Unmatched,
    ),
    (
        "comment needs no space",
        "#notes\n",
        "#notes",
        File,
        Unmatched,
    ),
    (
        "comment does not disable the next line",
        "# notes\nnotes\n",
        "notes",
        File,
        Ignore,
    ),
    (
        "hash after a leading space is data",
        " #notes\n",
        " #notes",
        File,
        Ignore,
    ),
    (
        "hash inside a pattern is data",
        "a#b\n",
        "a#b",
        File,
        Ignore,
    ),
    // Leading backslash makes `#` and `!` data.
    ("escaped hash", "\\#generated\n", "#generated", File, Ignore),
    ("escaped bang", "\\!retain\n", "!retain", File, Ignore),
    (
        "escaped bang is not a negation",
        "retain\n\\!retain\n",
        "retain",
        File,
        Ignore,
    ),
    (
        "bang inside a pattern is data",
        "a!b\n",
        "a!b",
        File,
        Ignore,
    ),
    // Trailing spaces.
    (
        "trailing spaces dropped",
        "cache   \n",
        "cache",
        File,
        Ignore,
    ),
    (
        "trailing spaces are not data",
        "cache   \n",
        "cache   ",
        File,
        Unmatched,
    ),
    (
        "escaped trailing space kept",
        "name\\ \n",
        "name ",
        File,
        Ignore,
    ),
    (
        "escaped trailing space is required",
        "name\\ \n",
        "name",
        File,
        Unmatched,
    ),
    (
        "spaces after an escaped space dropped",
        "name\\   \n",
        "name ",
        File,
        Ignore,
    ),
    (
        "space after an escaped backslash dropped",
        "a\\\\ \n",
        "a\\",
        File,
        Ignore,
    ),
    ("leading space is data", " lead\n", " lead", File, Ignore),
    (
        "leading space is required",
        " lead\n",
        "lead",
        File,
        Unmatched,
    ),
    (
        "inner space is data",
        "two words\n",
        "two words",
        File,
        Ignore,
    ),
    // `?` is exactly one byte, never a separator.
    ("question", "file?.txt\n", "file1.txt", File, Ignore),
    (
        "question is not two bytes",
        "file?.txt\n",
        "file12.txt",
        File,
        Unmatched,
    ),
    ("question is not zero bytes", "q?\n", "q", File, Unmatched),
    (
        "question is one byte, not one scalar",
        "q?\n",
        "qé",
        File,
        Unmatched,
    ),
    (
        "two questions take a two-byte scalar",
        "q??\n",
        "qé",
        File,
        Ignore,
    ),
    (
        "question never matches a separator",
        "x/a?b\n",
        "x/a/b",
        File,
        Unmatched,
    ),
    // `*` is any run of non-separator bytes, including none.
    (
        "star run is one star",
        "draft***.bak\n",
        "draft-final.bak",
        File,
        Ignore,
    ),
    (
        "star matches empty",
        "draft*.bak\n",
        "draft.bak",
        File,
        Ignore,
    ),
    (
        "unanchored star pattern tests the basename only",
        "draft***.bak\n",
        "draft/x.bak",
        File,
        Unmatched,
    ),
    (
        "star stops at a separator",
        "x/draft*.bak\n",
        "x/draft/y.bak",
        File,
        Unmatched,
    ),
    (
        "star within one component",
        "foo/*\n",
        "foo/test.json",
        File,
        Ignore,
    ),
    (
        "star stops at slash beneath a re-included directory",
        "foo/*\n!foo/*/\n",
        "foo/bar/hello.c",
        File,
        Unmatched,
    ),
    (
        "star before an extension stops at a separator",
        "x/*.c\n",
        "x/y/z.c",
        File,
        Unmatched,
    ),
    ("anchored star run", "x/a***b\n", "x/aqqb", File, Ignore),
    ("ordinary star run", "a***b\n", "axxxb", File, Ignore),
    ("star matches hidden", "*\n", ".hidden", File, Ignore),
    (
        "leading dot is not special",
        "*.bak\n",
        ".bak",
        File,
        Ignore,
    ),
    // Backslash escapes.
    ("escaped star", "\\*.txt\n", "*.txt", File, Ignore),
    ("escaped star is literal", "raw\\*\n", "raw*", File, Ignore),
    (
        "escaped star is not a wildcard",
        "raw\\*\n",
        "rawx",
        File,
        Unmatched,
    ),
    (
        "escaped question is not a wildcard",
        "raw\\?\n",
        "rawx",
        File,
        Unmatched,
    ),
    (
        "escaped question is literal",
        "raw\\?\n",
        "raw?",
        File,
        Ignore,
    ),
    (
        "escaped bracket is literal",
        "\\[ab]\n",
        "[ab]",
        File,
        Ignore,
    ),
    (
        "escaped bracket opens no class",
        "\\[ab]\n",
        "a",
        File,
        Unmatched,
    ),
    ("escaped ordinary bytes", "\\a\\b\n", "ab", File, Ignore),
    ("escaped backslash", "\\\\\n", "\\", File, Ignore),
    (
        "escaped slash separates",
        "pkg\\/bin\n",
        "pkg/bin",
        File,
        Ignore,
    ),
    (
        "escaped slash anchors",
        "pkg\\/bin\n",
        "x/pkg/bin",
        File,
        Unmatched,
    ),
    (
        "escaped slash beside a globstar",
        "a\\/**/b\n",
        "a/b",
        File,
        Ignore,
    ),
    // Case sensitivity.
    (
        "matching is case-sensitive",
        "*.TXT\n",
        "report.txt",
        File,
        Unmatched,
    ),
    ("same case matches", "*.TXT\n", "REPORT.TXT", File, Ignore),
    ("a bare slash matches nothing", "/\n", "x", File, Unmatched),
    (
        "a bare slash matches no directory",
        "/\n",
        "x",
        Dir,
        Unmatched,
    ),
    // Earlier spellings of the cases above, kept verbatim.
    (
        "comment, earlier spelling",
        "# generated\n",
        "# generated",
        File,
        Unmatched,
    ),
    (
        "escaped hash, earlier spelling",
        "\\#notes\n",
        "#notes",
        File,
        Ignore,
    ),
    (
        "escaped bang, earlier spelling",
        "\\!keep\n",
        "!keep",
        File,
        Ignore,
    ),
    (
        "trailing spaces, earlier spelling",
        "plain   \n",
        "plain",
        File,
        Ignore,
    ),
    ("quoted space", "quoted\\ \n", "quoted ", File, Ignore),
    (
        "quoted space differs",
        "quoted\\ \n",
        "quoted",
        File,
        Unmatched,
    ),
];

/// Lines that are reported as errors and never match.
pub(super) const INVALID_ROWS: &[Row] = &[
    (
        "trailing backslash",
        "unfinished\\\n",
        "unfinished\\",
        File,
        Unmatched,
    ),
    (
        "trailing backslash is not dropped",
        "unfinished\\\n",
        "unfinished",
        File,
        Unmatched,
    ),
    (
        "trailing backslash after an escaped one",
        "a\\\\\\\n",
        "a\\",
        File,
        Unmatched,
    ),
    (
        "bad line spares the others",
        "bad\\\nother\n",
        "other",
        File,
        Ignore,
    ),
];

/// Paths that are not UTF-8.
pub(super) fn byte_cases() -> Vec<Case> {
    [
        (
            "question matches one non-UTF-8 byte",
            "f?\n",
            &b"f\xff"[..],
            Ignore,
        ),
        ("star matches non-UTF-8 bytes", "f*\n", b"f\xfe\xff", Ignore),
        (
            "literal non-UTF-8 byte differs",
            "fx\n",
            b"f\xff",
            Unmatched,
        ),
    ]
    .into_iter()
    .map(|(label, patterns, path, want)| Case {
        label: label.to_owned(),
        patterns: patterns.to_owned(),
        path: path.to_vec(),
        kind: File,
        want,
    })
    .collect()
}

#[test]
fn line_syntax() {
    assert_rows(ROWS);
}

#[test]
fn non_utf8_paths() {
    assert_cases(byte_cases());
}

#[test]
fn invalid_lines_never_match() {
    for case in INVALID_ROWS.iter().map(Case::from) {
        assert_eq!(case.matched().0, case.want, "{}", case.describe());
    }
}

#[test]
fn invalid_line_is_reported_with_its_number_and_text() {
    let (matcher, errors) = Gitignore::compile("ok\nbad\\\nalso\n");
    let reported: Vec<_> = errors
        .iter()
        .map(|error| (error.line, error.pattern.as_str()))
        .collect();
    assert_eq!(reported, [(2, "bad\\")]);
    assert_eq!(matcher.matched(Path::new("ok"), false), Ignore);
    assert_eq!(matcher.matched(Path::new("also"), false), Ignore);
}

#[test]
fn pathological_stars_have_bounded_work() {
    const TEXT: &str = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    let (matcher, errors) = Gitignore::compile("*a*a*a*a*a*a*a*a*a*b\n");
    assert!(errors.is_empty());
    assert_eq!(matcher.matched(Path::new(TEXT), false), Unmatched);
    let pattern = match Pattern::compile(0, "*a*a*a*a*a*a*a*a*a*b") {
        Ok(Some(pattern)) => pattern,
        other => panic!("pathological pattern did not compile: {other:?}"),
    };
    let (matched, steps) = pattern.basename_match_steps(TEXT.as_bytes());
    assert!(!matched);
    // A backtracking matcher takes millions of steps here; the last-star
    // retry loop takes pattern x text at most.
    assert!(steps <= 1_000, "iterative matcher used {steps} steps");
}
