//! Line syntax: blanks, comments, escapes, trailing spaces, `?` and `*`.

use super::super::Pattern;
use super::{Case, Dir, File, Ignore, OneFile, Row, Unmatched, assert_cases, assert_rows, matched};

pub(super) const ROWS: &[Row] = &[
    // Blank and comment lines.
    ("blank line", "\n", "anything", File, Unmatched),
    ("spaces-only line is blank", "   \n", " ", File, Unmatched),
    (
        "comment",
        "# generated by build\n",
        "# generated by build",
        File,
        Unmatched,
    ),
    (
        "comment needs no space",
        "#notes\n",
        "#notes",
        File,
        Unmatched,
    ),
    (
        "comment does not disable the next line",
        "# notes\nnotes\n",
        "notes",
        File,
        Ignore,
    ),
    (
        "hash after a leading space is data",
        " #notes\n",
        " #notes",
        File,
        Ignore,
    ),
    (
        "hash inside a pattern is data",
        "a#b\n",
        "a#b",
        File,
        Ignore,
    ),
    // Leading backslash makes `#` and `!` data.
    ("escaped hash", "\\#generated\n", "#generated", File, Ignore),
    ("escaped bang", "\\!retain\n", "!retain", File, Ignore),
    (
        "escaped bang is not a negation",
        "retain\n\\!retain\n",
        "retain",
        File,
        Ignore,
    ),
    (
        "bang inside a pattern is data",
        "a!b\n",
        "a!b",
        File,
        Ignore,
    ),
    // Trailing spaces.
    (
        "trailing spaces dropped",
        "cache   \n",
        "cache",
        File,
        Ignore,
    ),
    (
        "trailing spaces are not data",
        "cache   \n",
        "cache   ",
        File,
        Unmatched,
    ),
    (
        "escaped trailing space kept",
        "name\\ \n",
        "name ",
        File,
        Ignore,
    ),
    (
        "escaped trailing space is required",
        "name\\ \n",
        "name",
        File,
        Unmatched,
    ),
    (
        "spaces after an escaped space dropped",
        "name\\   \n",
        "name ",
        File,
        Ignore,
    ),
    (
        "space after an escaped backslash dropped",
        "a\\\\ \n",
        "a\\",
        File,
        Ignore,
    ),
    ("leading space is data", " lead\n", " lead", File, Ignore),
    (
        "leading space is required",
        " lead\n",
        "lead",
        File,
        Unmatched,
    ),
    (
        "inner space is data",
        "two words\n",
        "two words",
        File,
        Ignore,
    ),
    // `?` is exactly one byte, never a separator.
    ("question", "file?.txt\n", "file1.txt", File, Ignore),
    (
        "question is not two bytes",
        "file?.txt\n",
        "file12.txt",
        File,
        Unmatched,
    ),
    ("question is not zero bytes", "q?\n", "q", File, Unmatched),
    (
        "question is one byte, not one scalar",
        "q?\n",
        "qé",
        File,
        Unmatched,
    ),
    (
        "two questions take a two-byte scalar",
        "q??\n",
        "qé",
        File,
        Ignore,
    ),
    (
        "question never matches a separator",
        "x/a?b\n",
        "x/a/b",
        File,
        Unmatched,
    ),
    // `*` is any run of non-separator bytes, including none.
    (
        "star run is one star",
        "draft***.bak\n",
        "draft-final.bak",
        File,
        Ignore,
    ),
    (
        "star matches empty",
        "draft*.bak\n",
        "draft.bak",
        File,
        Ignore,
    ),
    (
        "unanchored star pattern tests the basename only",
        "draft***.bak\n",
        "draft/x.bak",
        File,
        Unmatched,
    ),
    (
        "star stops at a separator",
        "x/draft*.bak\n",
        "x/draft/y.bak",
        File,
        Unmatched,
    ),
    (
        "star within one component",
        "foo/*\n",
        "foo/test.json",
        File,
        Ignore,
    ),
    (
        "star stops at slash beneath a re-included directory",
        "foo/*\n!foo/*/\n",
        "foo/bar/hello.c",
        File,
        Unmatched,
    ),
    (
        "star before an extension stops at a separator",
        "x/*.c\n",
        "x/y/z.c",
        File,
        Unmatched,
    ),
    ("anchored star run", "x/a***b\n", "x/aqqb", File, Ignore),
    ("ordinary star run", "a***b\n", "axxxb", File, Ignore),
    ("star matches hidden", "*\n", ".hidden", File, Ignore),
    (
        "leading dot is not special",
        "*.bak\n",
        ".bak",
        File,
        Ignore,
    ),
    // Backslash escapes.
    ("escaped star", "\\*.txt\n", "*.txt", File, Ignore),
    ("escaped star is literal", "raw\\*\n", "raw*", File, Ignore),
    (
        "escaped star is not a wildcard",
        "raw\\*\n",
        "rawx",
        File,
        Unmatched,
    ),
    (
        "escaped question is not a wildcard",
        "raw\\?\n",
        "rawx",
        File,
        Unmatched,
    ),
    (
        "escaped question is literal",
        "raw\\?\n",
        "raw?",
        File,
        Ignore,
    ),
    (
        "escaped bracket is literal",
        "\\[ab]\n",
        "[ab]",
        File,
        Ignore,
    ),
    (
        "escaped bracket opens no class",
        "\\[ab]\n",
        "a",
        File,
        Unmatched,
    ),
    ("escaped ordinary bytes", "\\a\\b\n", "ab", File, Ignore),
    ("escaped backslash", "\\\\\n", "\\", File, Ignore),
    (
        "escaped slash separates",
        "pkg\\/bin\n",
        "pkg/bin",
        File,
        Ignore,
    ),
    (
        "escaped slash anchors",
        "pkg\\/bin\n",
        "x/pkg/bin",
        File,
        Unmatched,
    ),
    (
        "escaped slash beside a globstar",
        "a\\/**/b\n",
        "a/b",
        File,
        Ignore,
    ),
    (
        "escaped leading slash is not an anchor",
        "\\/probe\n",
        "probe",
        File,
        Unmatched,
    ),
    (
        "escaped trailing slash is not directory-only",
        "crates\\/\n",
        "crates",
        Dir,
        Unmatched,
    ),
    (
        "escaped separator after globstar needs a directory",
        "**\\/probe\n",
        "probe",
        File,
        Unmatched,
    ),
    (
        "escaped separator after globstar matches one directory",
        "**\\/probe\n",
        "x/probe",
        File,
        Ignore,
    ),
    (
        "escaped separator after globstar matches many directories",
        "**\\/probe\n",
        "x/y/probe",
        File,
        Ignore,
    ),
    (
        "escaped separator after middle globstar needs a directory",
        "a/**\\/b\n",
        "a/b",
        File,
        Unmatched,
    ),
    // Case sensitivity.
    (
        "matching is case-sensitive",
        "*.TXT\n",
        "report.txt",
        File,
        Unmatched,
    ),
    ("same case matches", "*.TXT\n", "REPORT.TXT", File, Ignore),
    ("a bare slash matches nothing", "/\n", "x", File, Unmatched),
    (
        "a bare slash matches no directory",
        "/\n",
        "x",
        Dir,
        Unmatched,
    ),
    ("quoted space", "quoted\\ \n", "quoted ", File, Ignore),
    (
        "quoted space differs",
        "quoted\\ \n",
        "quoted",
        File,
        Unmatched,
    ),
];

/// Lines that are reported as errors and never match.
pub(super) const INVALID_ROWS: &[Row] = &[
    (
        "trailing backslash",
        "unfinished\\\n",
        "unfinished\\",
        File,
        Unmatched,
    ),
    (
        "trailing backslash is not dropped",
        "unfinished\\\n",
        "unfinished",
        File,
        Unmatched,
    ),
    (
        "trailing backslash after an escaped one",
        "a\\\\\\\n",
        "a\\",
        File,
        Unmatched,
    ),
    (
        "bad line spares the others",
        "bad\\\nother\n",
        "other",
        File,
        Ignore,
    ),
];

/// Paths that are not UTF-8.
pub(super) fn byte_cases() -> Vec<Case> {
    [
        (
            "question matches one non-UTF-8 byte",
            "f?\n",
            &b"f\xff"[..],
            Ignore,
        ),
        ("star matches non-UTF-8 bytes", "f*\n", b"f\xfe\xff", Ignore),
        (
            "literal non-UTF-8 byte differs",
            "fx\n",
            b"f\xff",
            Unmatched,
        ),
    ]
    .into_iter()
    .map(|(label, patterns, path, want)| Case {
        label: label.to_owned(),
        patterns: patterns.to_owned(),
        path: path.to_vec(),
        kind: File,
        want,
    })
    .collect()
}

#[test]
fn line_syntax() {
    assert_rows(ROWS);
}

#[test]
fn non_utf8_paths() {
    assert_cases(byte_cases());
}

#[test]
fn invalid_lines_never_match() {
    for case in INVALID_ROWS.iter().map(Case::from) {
        assert_eq!(case.matched().0, case.want, "{}", case.describe());
    }
}

#[test]
fn invalid_line_is_reported_with_its_number_and_text() {
    let (matcher, errors) = OneFile::compile("ok\nbad\\\nalso\n");
    let reported: Vec<_> = errors
        .iter()
        .map(|error| (error.line, error.pattern.as_str()))
        .collect();
    assert_eq!(reported, [(2, "bad\\")]);
    assert_eq!(matched(&matcher, b"ok", false), Ignore);
    assert_eq!(matched(&matcher, b"also", false), Ignore);
}

#[test]
fn pathological_stars_have_bounded_work() {
    for n in [64, 256, 1024] {
        let text = "a".repeat(n);
        let stars = format!("{}b", "*a".repeat(n / 8));
        let literals = format!("{}b", "a".repeat(n));
        let classes = format!("{}b", "[a]".repeat(n / 8));
        for (label, source, path) in [
            ("star runs", stars, text.clone()),
            ("long literal", literals, format!("{text}c")),
            ("classes", classes, format!("{text}c")),
        ] {
            let pattern = Pattern::compile(0, &source).unwrap().unwrap();
            let (matched, steps) = pattern.basename_match_steps(path.as_bytes());
            assert!(!matched, "{label} unexpectedly matched at n={n}");
            // Counts matcher loop/retry iterations. Literal byte comparisons,
            // class-term scans, and fast-bucket probes are not included; each
            // is bounded by the compiled pattern width per matcher iteration.
            let bound = 8 * source.len() * path.len();
            assert!(steps <= bound, "{label} n={n}: {steps} > {bound}");
        }

        // An anchored pattern is stepped a directory at a time. Its cursors
        // are deduplicated by position, so however many components the path
        // has, each step does at most one component match per pattern
        // component, each bounded as above.
        let source = "**/a*/b";
        let path = format!("{}{}/c", "x/".repeat(n / 2), "a".repeat(n));
        let pattern = Pattern::compile(0, source).unwrap().unwrap();
        let (parents, _) = path.rsplit_once('/').unwrap();
        let mut cursors = vec![(0, false)];
        for parent in parents.split('/') {
            let mut next = Vec::new();
            pattern.step(cursors, parent.as_bytes(), &mut next);
            assert!(
                next.len() <= pattern.component_count(),
                "globstar cursors n={n}: {next:?}"
            );
            cursors = next;
        }
        let (matcher, _) = OneFile::compile(source);
        assert_eq!(matched(&matcher, path.as_bytes(), false), Unmatched);
    }
}

#[test]
fn globstar_runs_have_bounded_work() {
    let n = 10_000;
    // A run of `**/` compiles to one globstar, so this is `**/hit`.
    let plain = format!("{}hit", "**/".repeat(n));
    // Globstars separated by literals do not collapse: 2n + 1 components,
    // and a chain of `a` directories leaves a cursor on every globstar and
    // literal it has reached.
    let alternating = format!("{}hit", "**/a/".repeat(n));
    let chain = "a/".repeat(200);
    for (label, source, path, expected) in [
        ("plain", &plain, "a/b/hit".to_owned(), Ignore),
        ("plain", &plain, "a/b/x".to_owned(), Unmatched),
        (
            "alternating",
            &alternating,
            format!("{chain}hit"),
            Unmatched,
        ),
        (
            "alternating",
            &alternating,
            format!("{chain}b/hit"),
            Unmatched,
        ),
    ] {
        let (matcher, errors) = OneFile::compile(source);
        assert!(errors.is_empty(), "{label}: {errors:?}");
        let words = source.len().div_ceil(64);
        crate::rules::take_step_work();
        assert_eq!(
            matched(&matcher, path.as_bytes(), false),
            expected,
            "{label} {path}"
        );
        let work = crate::rules::take_step_work();
        // A step visits each live cursor's component and, from a globstar,
        // the one after it: at most two visits per cursor. A directory adds
        // at most two cursors, and the position bitsets add a word scan per
        // step. The old recursion walked all n globstars of the plain form in
        // one step, and deduplicated the alternating form's cursors by linear
        // search, quadratic in the cursors per step.
        let steps = path.split('/').count() - 1;
        let bound = steps * (4 * (2 * steps + 1) + words + 4);
        assert!(work <= bound, "{label}, {steps} steps: {work} > {bound}");
    }
}
